// background.js

function removeDiacritics(str) {
  return str
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");
}

function normalizeForCheck(str) {
  let s = removeDiacritics(str);
  s = s.toUpperCase();
  s = s.replace(/[®™©]/g, "");
  s = s.replace(/[^A-Z0-9]/g, "");
  return s;
}

function cleanBrandList(arr) {
  const cleaned = [];
  for (const item of arr) {
    const norm = normalizeForCheck(item);
    if (norm.length >= 3) {
      cleaned.push(item);
    }
  }
  return cleaned;
}

chrome.runtime.onInstalled.addListener(() => {
  // If the environment doesn't support chrome.storage.sync, bail gracefully
  if (!chrome?.storage?.sync) {
    console.warn("chrome.storage.sync not available?");
    return;
  }

  chrome.storage.sync.get(
    [
      "cat1Canadian",
      "cat2Mexican",
      "cat3US",
      "cat4PartialUSCA",
      "cat5PartialUSMX",
      "cat6Outside"
    ],
    (data) => {

      // 1) Canadian (🍁)
      if (!data.cat1Canadian) {
        let cat1 = [
          "TIM HORTONS",
          "MAPLE LEAF",
          "PRESIDENT'S CHOICE",
          "LOBLAWS",
          "NO NAME",
          "COMPLIMENTS",
          "MCCAIN",
          "NEILSON",
          "NATREL",
          "CHAPMAN'S",
          "SAPUTO",
          "KICKING HORSE COFFEE",
          "CANADA DRY",
          "AGROPUR",
          "OKA",
          "GAY LEA",
          "QUEBON",
          "YOPLAIT (CANADA)",
          "CLUB HOUSE",
          "SWISS CHALET",
          "HARVEY'S",
          "MONTANA'S",
          "MR. SUB",
          "MARY BROWN'S",
          "DARE FOODS",
          "DAVIDSTEA",
          "FARM BOY",
          "FORTINOS",
          "GASPEREAU VINEYARDS",
          "GRANVILLE ISLAND BREWING",
          "GUERRERO (CA)",
          "HABITANT",
          "HARVEY & VERN'S",
          "JONES SODA (CAN)",
          "KERNALS POPCORN",
          "KRAFT CANADA",
          "LITTLE NORTHERN BAKEHOUSE",
          "MCCORMICK CANADA",
          "METRO",
          "MORTIMER'S",
          "MOTHER PARKERS",
          "NESTLÉ (CAN)",
          "OLYMEL",
          "OLIVIERI",
          "PACIFIC WESTERN BREWING",
          "PATTISON FOOD GROUP",
          "PEAK FREANS (CAN)",
          "PENGUIN ICE CREAM",
          "QUEBEC MAPLE SYRUP",
          "RED ROSE TEA (CAN)",
          "ROBERTSON'S",
          "ROYALE TISSUE",
          "SCHNEIDERS",
          "SCOTSBURN",
          "SELECTION (METRO)",
          "SMARTIES (CA VERSION)",
          "SO NICE (CAN)",
          "SOBEYS",
          "SUN RYPE",
          "THRIFTY FOODS",
          "VACHON",
          "WESTON FOODS",
          "WHITEWATER BREWING",
          "ACE BAKERY",
          "CANADA GOOSE",
          "BLACK FLY BEVERAGES",
          "BRIDOR",
          "BULK BARN",
          "CANADIAN CLUB",
          "CANADA SELECT",
          "CEDAR FOODS (CA)",
          "DAIRYLAND",
          "DEMPSTER'S",
          "DOMINION (GROCERY)",
          "ELASTOBAK FOODS",
          "FORT GARRY BREWING",
          "FRESHCO",
          "GOLD SEAL (SEAFOOD)",
          "GREEN & BLACK'S (CA DIV)",
          "HOP CITY BREWING",
          "IRRESISTIBLES",
          "JON MONTREAL BAGELS",
          "MARC ANGE",
          "MOUNTAINVIEW TURKEY",
          "NATUREGG",
          "NORREF SEAFOODS",
          "PACIFIC WILD",
          "POM BAKERY",
          "RICKARD'S",
          "SEAGRAM",
          "SENSATIONS (SAFEWAY)",
          "ST. HUBERT",
          "VILLAGGIO",
          "VOORTMAN",
          "WESTERN FAMILY",
          "ZARKY'S",
          "ZIGGY'S",
          "WEBBER NATURALS",
          "SMARTSWEETS",
          "RENEES",
          "BURNBRAE FARMS",
          "MISS VICKIE'S",
          "QUE PASA",
          "OLD DUTCH",
          "NEAL BROTHERS",
          "KETTLE BRAND",
          "UNICO",
          "FOREMOST DAIRIES",
          "GREAT GENTLEMAN",
          "GRACE ISLAND",
          "NABOB",
          "MCCAFE",
          "PILLERS",
          "RITZ",
          "CHRISTIE",
          "CHRISTIE'S",
          "OIKOS",
          "ACTIVIA",
          "DANONE",
          "YOPLAIT",
          "CLOVER LEAF",
          "SILVER HILLS BAKERY",
          "LITTLE NORTHERN BAKEHOUSE",
          "HABITANT",
          "GOLDEN DRAGON",
          "CATELLI",
          "DRUMSTICK",
          "SPITZ",
          "CALEDON FARMS",
          "SUNRISE TOFU",
          "SHORBA",
          "AYLMER",
          "MR. NOODLES",
          "M'LORD",
          "EVIVE",
          "WINDSOR",
          "ROGERS",
          "OLIVIERI",
          "ANTONIO",
          "YVES",
          "IOGO",
          "SEALTEST",
          "REMEDY ORGANICS",
          "CASA MENDOZA",
          "MADEGOOD",
          "DECACER",
          "NATURE'S PATH",
          "QUINN'S",
          "BALDERSON",
          "HAWKINS CHEEZIES",
          "ARVA FLOUR MILLS",
          "WONDERBRANDS",
          "STONE MILL BAKEHOUSE",
          "SUNNY BOY FOODS",
          "GREAT WESTERN BREWING",
          "OATALLY AWESOME",
          "PRIME CHICKEN (MAPLE LODGE)"
        ];
        cat1 = cleanBrandList(cat1);
        chrome.storage.sync.set({ cat1Canadian: cat1 });
      }

      // 2) Mexican (🇲🇽)
      if (!data.cat2Mexican) {
        let cat2 = [
          "BIMBO",
          "CORONA",
          "GRUPO MODELO",
          "MISSION FOODS (MX)",
          "BARCEL",
          "TAJIN",
          "HERDEZ",
          "LA COSTENA",
          "VELADORA",
          "GAMESA",
          "FRESCAS",
          "KERMATO",
          "BACARDI (MEX DIV)",
          "CARLOS V (CHOCOLATE)",
          "EMPERADOR",
          "MARINELA",
          "LA MORENA",
          "EMBASA (MX)",
          "VALENTINA SAUCE",
          "CAFE DE OLLA",
          "CHARRAS",
          "RUMBA MEATS",
          "FUD",
          "CHORIZO SAN MANUEL",
          "GRUMA",
          "AVOCADOS FROM MEXICO",
          "AGUASCALIENTES BREW",
          "CLAMATO (MEX DIV)",
          "DON JULIO (MX)"
        ];
        cat2 = cleanBrandList(cat2);
        chrome.storage.sync.set({ cat2Mexican: cat2 });
      }

      // 3) US (❌)
      if (!data.cat3US) {
        let cat3 = [
          "HOSTESS",
          "MUNCHIES",
          "COCA-COLA",
          "PEPSI",
          "FRITO-LAY",
          "HERSHEY'S",
          "CAMPBELL'S",
          "HEINZ",
          "KRAFT",
          "GENERAL MILLS",
          "KELLOGG'S",
          "TWINKIES",
          "BEN & JERRY'S",
          "LAY'S",
          "BUDWEISER",
          "CHEERIOS",
          "CHEEZ-IT",
          "CHEETOS",
          "OSCAR MAYER",
          "REESE'S",
          "HORMEL",
          "NABISCO",
          "OREO",
          "SNICKERS",
          "DR PEPPER",
          "FRANK'S REDHOT",
          "GATORADE",
          "BETTY CROCKER",
          "PILLSBURY",
          "STARBUCKS",
          "M&M'S",
          "WHEAT THINS",
          "TRISCUIT",
          "PRINGLES",
          "CHEX",
          "FROOT LOOPS",
          "FROSTED FLAKES",
          "POP-TARTS",
          "EGGO",
          "STOUFFER'S",
          "HOT POCKETS",
          "MARIE CALLENDER'S",
          "AMY'S",
          "DIET COKE",
          "SPRITE",
          "MOUNTAIN DEW",
          "DORITOS",
          "TOSTITOS",
          "FRITOS",
          "RUFFLES",
          "SUN CHIPS",
          "HOSTESS CUPCAKES",
          "WHITE CASTLE",
          "CALIFORNIA PIZZA KITCHEN",
          "RED BARON",
          "TOMBSTONE",
          "TONY'S",
          "TOTINO'S",
          "HUNT'S",
          "RO-TEL",
          "VELVEETA",
          "PHILADELPHIA",
          "COOL WHIP",
          "MIRACLE WHIP",
          "JELL-O",
          "KRAFT MAC & CHEESE",
          "VELVEETA SHELLS & CHEESE",
          "CHEEZ WHIZ",
          "A1 SAUCE",
          "LEA & PERRINS",
          "WISH-BONE",
          "MAZOLA",
          "CRISCO",
          "PAM",
          "ORVILLE REDENBACHER'S",
          "PETER PAN",
          "SKIPPY",
          "JIF",
          "SCHWEPPES",
          // "A&W" removed due to short length => "AW"
          "BARQ'S",
          "ROOT BEER",
          "CRYSTAL LIGHT",
          "COUNTRY TIME",
          "TANG",
          "HI-C",
          "KOMBUCHA WONDER DRINK",
          "CLIF BAR",
          "LUNA BAR",
          "POWERBAR",
          "SLIMFAST",
          "BOSTON MARKET",
          "BANQUET",
          "TYSON",
          "PERDUE",
          "HIDDEN VALLEY",
          "RANCH",
          "FRENCH'S",
          "GULDEN'S",
          "GREY POUPON",
          "HELLMANN'S",
          "BEST FOODS",
          "DUKE'S",
          "MILK-BONE",
          "BEGGIN",
          "CLARITIN",
          "BEYOND MEAT",
          "BODYARMOR",
          "ZEVIA",
          "MINUTE RICE",
          "LUNDBERG FAMILY FARMS",
          "KNORR",
          "MICHELINA'S",
          "TEMPTATIONS",
          "PEPPERIDGE",
          "NESTLE",
          "ENJOY LIFE",
          "GT'S",
          "SKY VALLEY",
          "ROLD GOLD PRETZELS",
          "QUAKER",
          "SIETE",
          "TAKIS",
          "BUSH'S BEANS",
          "CRUSH",
          "FANTA",
          "BUBLY",
          "SPARKLING ICE",
          "BAI",
          "VITAMINWATER",
          "PROPEL",
          "MAXWELL HOUSE",
          "FOLGERS",
          "STOK",
          "POWERADE",
          "OCEAN SPRAY",
          "MOTT'S",
          "FUZE",
          "CELSIUS",
          "MONSTER",
          "NESQUIK",
          "CARNATION",
          "ENSURE",
          "WEIGHT WATCHERS",
          "GOGO SQUEEZ",
          "AWAKE",
          "SMARTIES",
          "HARIBO",
          "JACK LINKS",
          "SLIM JIM",
          "GUSHERS",
          "HUBBA BUBBA",
          "DOLE",
          "STACY'S",
          "TYLENOL",
          "CASCADE",
          "SWIFFER",
          "THAI KITCHEN",
          "PEPCID",
          "BOB'S RED MILL",
          "MIO",
          "CRISPERS",
          "ADAMS",
          "SILK",
          "CRACKER BARREL",
          "OLD EL PASO",
          "LUNDBERG",
          "DENTALIFE",
          "PEDIGREE",
          "WONDERFUL",
          "POM",
          "ANCHOR'S BAY",
          "AVALON",
          "LUCERNE",
          "HERBAL ESSENCES",
          "SELSUN BLUE",
          "PRIME",
          "DEL MONTE",
          "IMAGINE",
          "PURITAN'S PRIDE",
          "BUSH'S BEST",
          "CHEF BOYARDEE",
          "GREEN GIANT",
          "DEL MONTE",
          "HEINZ",
          "TAST!EZ",
          "CRAVE",
          "SMART ONES",
          "MINUTE MAID",
          "CLUB HOUSE",
          "CESAR",
          "CELSIUS",
          "CASCADE",
          "WELCH'S",
          "PURE PROTEIN",
          "GODIVA",
          "ARM & HAMMER",
          "ALMOND BREEZE",
          "44TH STREET",
          "GREAT VALUE",
          "MANNS",
          "SWANSON'S",
          "PLANTERS",
          "OCEAN SPRAY",
          "SWEET BABY RAY'S",
          "HARTZ",
          "NEILMED",
          "OLAY",
          "NEUTROGENA",
          "AUSSIE",
          "BATISTE",
          "ENERGIZER",
          "DURACELL",
          "KODIAK",
          "POST",
          "CINNAMON TOAST CRUNCH",
          "SMUCKER'S",
          "NATURE VALLEY",
          "LUCKY CHARMS",
          "CREAM OF WHEAT",
          "CORN POPS",
          "KELLOGG",
          "CHEERIOS",
          "KRAVE",
          "HUNGRY JACK'S",
          "CAP'N CRUNCH",
          "GENERAL MILLS",
          "KIRKLAND"
        ];
        cat3 = cleanBrandList(cat3);
        chrome.storage.sync.set({ cat3US: cat3 });
      }

      // 4) Partial US/CA (❓)
      if (!data.cat4PartialUSCA) {
        let cat4 = [
          "KRAFT DINNER (KD)",
          "PURDY'S (US/CA JOINT)",
          "SMITHFIELD MAPLE",
          "QUAKER (MADE IN CANADA, US PARENT)",
          "JOHNSONVILLE (US BRAND, MADE IN CANADA)",
          "DARE FOODS (CA BRAND, US FACTORY)",
          "OLD DUTCH (CAN/US SPLIT)",
          "SUN MAID (US BRAND, PACKED IN CA)",
          "NESTLÉ TURTLES (US COMPANY, MADE IN CANADA)",
          "HERSHEY KISSES (US, MADE IN CANADA)",
          "CAMPBELL SOUP (US, CAN PLANT)",
          "CHEEZ WHIZ (US BRAND, CAN FACTORY)",
          "WONKA (US, CAN FACTORY)",
          "CINNABON (US BRAND, SOME CA LOCATIONS)",
          "CRACKER BARREL CHEESE (US/CA CROSSOVER)",
          "MAPLE LODGE (CA MEAT, US OWNED)",
          "COCA-COLA (US COMPANY, BOTTLED IN CANADA)",
          "LABATT (CA, OWNED BY AB-INBEV US)",
          "TIM HORTONS (CA, OWNED BY US PARENT)",
          "UNCLE BEN'S (US BRAND, RICE GROWN IN CANADA?)",
          "SARA LEE (US, CAN SUBSIDIARY)",
          "BEN & JERRY'S (US, SOME FLAVORS MADE IN CA)",
          "GENERAL MILLS (US, CAN FACTORY)",
          "FRENCH'S KETCHUP (US BRAND, TOMATOES FROM CA)",
          "SIMPLY ORANGE (US BRAND, SOME ORANGES FROM CA)",
          "AIR CANADA + UNITED CROSS SNACK",
          "BUD LIGHT (US, BREWED PARTIALLY IN CANADA)",
          "SUN CHIPS (US, SOME PRODUCTS IN CA)",
          "REESE MINI (US, MADE IN CANADA)",
          "NILLA WAFERS (US, BAKED IN CA)",
          "HELLMANN'S (US BRAND, PRODUCED IN TORONTO)",
          "LAY'S (US BRAND, CANADIAN FACTORY)",
          "PEPSICO (US, CANADIAN BOTTLING)",
          "KELLOGG (US, SOME CEREALS IN CANADA)",
          "CASCADES (CAN CO, US PARTS)",
          "GLAD GARBAGE BAGS (US PARENT, MADE IN CA)",
          "UNILEVER (US/EU, BUT PRODUCTION PLANT IN CANADA)",
          "NESTLÉ (GLOBAL, SOME PRODUCTS MADE IN CANADA)",
          "HAAGEN-DAZS (GLOBAL, US PARTNERSHIP, SOME PRODUCTION IN CA)",
          "BREYERS (US, ALSO MADE IN CANADA)"
        ];
        cat4 = cleanBrandList(cat4);
        chrome.storage.sync.set({ cat4PartialUSCA: cat4 });
      }

      // 5) Partial US/Mexico (❔)
      if (!data.cat5PartialUSMX) {
        let cat5 = [
          "KRAFT (US) USING MEX PLANT",
          "COCA-COLA (US) BOTTLED IN MEXICO",
          "FANTA (US BRAND, MX PRODUCTION)",
          "GAMESA (MX, US DISTRIBUTION)",
          "BARCEL TAKIS (MX, DISTRIBUTED BY US)",
          "MARINELA (MX, US PARTNERSHIP)",
          "WELCH'S MANGOS (US BRAND, MEX FRUIT)",
          "MISSION TORTILLAS (US & MEX DIV)",
          "DE LA ROSA PEANUT CONFECTION (MX, US PART OWNER)",
          "NESTLÉ (US DIV, MEX FACTORY)",
          "PEPSICO (US), MEXICO BOTTLERS",
          "LAY'S (US), SABRITAS (MX)",
          "HERSHEY'S CHOCOLATE W/ MEX COCOA",
          "MEXICOKE (COCA-COLA MEXICO, US BRAND)",
          "BIMBO (MX), SARA LEE (US) CROSSOVER",
          "CORN NUTS (US) MFG IN MEX",
          "DORITOS TACO FLAVOR (MIXED US/MX)",
          "COLGATE PALMOLIVE (US/MX JOINT)",
          "MCCORMICK (US) SALSA MEX PLANT",
          "TYSON (US) CHICKEN FROM MEXICO",
          "DR PEPPER MEXICO (US BRAND, MEX PLANT)",
          "FRITO-LAY MEXICO (US BRAND)",
          "BACARDI US/MEX PLANT",
          "UNCLE BEN'S (US) RICE FROM MEX",
          "QUAKER OATS (US) MFG IN MEX"
        ];
        cat5 = cleanBrandList(cat5);
        chrome.storage.sync.set({ cat5PartialUSMX: cat5 });
      }

      // 6) Outside any (🌐)
      if (!data.cat6Outside) {
        let cat6 = [
          "FERRERO (ITALY)",
          "NUTELLA",
          "KITKAT (UK OR JP DIV)",
          "NISSIN (JAPAN)",
          "UNILEVER (EU)",
          "NESCAFÉ (SWITZERLAND DIV)",
          "SAMSUNG FOODS (S KOREA)",
          "HITACHI RICE (JAPAN)",
          "YILI (CHINA)",
          "HARIBO (GERMANY)",
          "NUTRESA (COLOMBIA)",
          "TCHIBO (GERMANY)",
          "KINDER (ITALY)",
          "MILKA (GERMANY, MONDELEZ)",
          "BELGIAN CHOCS (BELGIUM)",
          "CADBURY (UK DIV)",
          "TOBLERONE (SWITZERLAND)",
          "MAGGI (SWITZERLAND)",
          "LINDT (SWITZERLAND)",
          "ALPEN (UK)",
          "DANONE (FRANCE)",
          "GLAXO FOOD (UK)",
          "ARLA (DENMARK)",
          "ANCHOR BUTTER (NEW ZEALAND)",
          "DUTCH LADY (NETHERLANDS)",
          "LOTTE (S KOREA)",
          "MARUTAI (JAPAN)",
          "PLAZA BISCUITS (SERBIA)",
          "AHMAD TEA (UK)",
          "MELLIN (ITALY)"
        ];
        cat6 = cleanBrandList(cat6);
        chrome.storage.sync.set({ cat6Outside: cat6 });
      }
    }
  );
});

chrome.runtime.onMessage.addListener((req, sender, sendResponse) => {
  if (req.type === "updateBrands6") {
    chrome.storage.sync.set({
      cat1Canadian: req.cat1Canadian,
      cat2Mexican: req.cat2Mexican,
      cat3US: req.cat3US,
      cat4PartialUSCA: req.cat4PartialUSCA,
      cat5PartialUSMX: req.cat5PartialUSMX,
      cat6Outside: req.cat6Outside
    }, () => sendResponse({ status: "ok" }));
    return true;
  }
});
