// background.js

chrome.runtime.onInstalled.addListener(() => {
  console.log("Instacart Extension: background installed/updated.");

  chrome.storage.sync.get(["usBrands", "caBrands"], (data) => {

    if (!data.usBrands) {
      const usDefaults = [
        "HOSTESS",
        "MUNCHIES",
        "COCA-COLA",
        "PEPSI",
        "FRITO-LAY",
        "HERSHEY\'S",
        "CAMPBELL\'S",
        "HEINZ",
        "KRAFT",
        "GENERAL MILLS",
        "KELLOGG\'S",
        "TWINKIES",
        "BEN & JERRY\'S",
        "LAY\'S",
        "BUDWEISER",
        "CHEERIOS",
        "CHEEZ-IT",
        "CHEETOS",
        "OSCAR MAYER",
        "REESE\'S",
        "HORMEL",
        "NABISCO",
        "OREO",
        "SNICKERS",
        "DR PEPPER",
        "FRANK\'S REDHOT",
        "GATORADE",
        "BETTY CROCKER",
        "PILLSBURY",
        "STARBUCKS",
        "M&M\'S",
        "WHEAT THINS",
        "TRISCUIT",
        "PRINGLES",
        "CHEX",
        "FROOT LOOPS",
        "FROSTED FLAKES",
        "POP-TARTS",
        "EGGO",
        "STOUFFER\'S",
        "HOT POCKETS",
        "MARIE CALLENDER\'S",
        "AMY\'S",
        "DIET COKE",
        "SPRITE",
        "MOUNTAIN DEW",
        "DORITOS",
        "TOSTITOS",
        "FRITOS",
        "RUFFLES",
        "SUN CHIPS",
        "HOSTESS CUPCAKES",
        "WHITE CASTLE",
        "CALIFORNIA PIZZA KITCHEN",
        "RED BARON",
        "TOMBSTONE",
        "TONY\'S",
        "TOTINO\'S",
        "HUNT\'S",
        "RO-TEL",
        "VELVEETA",
        "PHILADELPHIA",
        "COOL WHIP",
        "MIRACLE WHIP",
        "JELL-O",
        "KRAFT MAC & CHEESE",
        "VELVEETA SHELLS & CHEESE",
        "CHEEZ WHIZ",
        "A1 SAUCE",
        "LEA & PERRINS",
        "WISH-BONE",
        "MAZOLA",
        "CRISCO",
        "PAM",
        "ORVILLE REDENBACHER\'S",
        "PETER PAN",
        "SKIPPY",
        "JIF",
        "SCHWEPPES",
        "A&W",
        "BARQ\'S",
        "ROOT BEER",
        "CRYSTAL LIGHT",
        "COUNTRY TIME",
        "TANG",
        "HI-C",
        "KOMBUCHA WONDER DRINK",
        "CLIF BAR",
        "LUNA BAR",
        "POWERBAR",
        "SLIMFAST",
        "BOSTON MARKET",
        "BANQUET",
        "TYSON",
        "PERDUE",
        "HIDDEN VALLEY",
        "RANCH",
        "FRENCH\'S",
        "GULDEN\'S",
        "GREY POUPON",
        "HELLMANN\'S",
        "BEST FOODS",
        "DUKE\'S",
        "MILK-BONE",
        "BEGGIN",
        "CLARITIN",
        "BEYOND MEAT",
        "BODYARMOR",
        "ZEVIA",
        "MINUTE RICE",
        "LUNDBERG FAMILY FARMS",
        "KNORR",
        "MICHELINA\'S",
        "TEMPTATIONS",
        "PEPPERIDGE FARM",
        "NESTLE",
        "ENJOY LIFE",
        "GT\'S",
        "SKY VALLEY",
        "ROLD GOLD PRETZELS",
        "QUAKER",
        "SIETE",
        "TAKIS",
        "BUSH'S BEANS",
        "CRUSH",
        "FANTA",
        "BUBLY",
        "SPARKLING ICE",
        "BAI",
        "VITAMINWATER",
        "PROPEL",
        "MAXWELL HOUSE",
        "FOLGERS",
        "STOK",
        "POWERADE",
        "OCEAN SPRAY",
        "MOTT'S",
        "FUZE",
        "CELSIUS",
        "MONSTER",
        "NESQUIK",
        "CARNATION",
        "ENSURE",
        "WEIGHT WATCHERS",
        "GOGO SQUEEZ",
        "AWAKE",
        "SMARTIES",
        "HARIBO",
        "JACK LINKS",
        "SLIM JIM",
        "GUSHERS",
        "BETTY CROCKER",
        "FIBER ONE",
        "SNYDERS",
        "BLUE DIAMOND",
        "JELL-O",
        "EXCEL",
        "TIC TAC",
        "HUBBA BUBBA",
        "DOLE", 
        "STACY'S",
        "BEYOND MEAT", 
        "PEPPERIDGE FARM", 
        "TYLENOL",
        "CASCADE", 
        "SWIFFER",
        "THAI KITCHEN",
        "PEPCID",
        "BOB'S RED MILL", 
        "MIO", 
        "CRISPERS",
        "ADAMS", 
        "BUTTERBALL", 
        "SILK",
        "CRACKER BARREL", 
        "OLD EL PASO", 
        "LUNDBERG",
        "DENTALIFE",
        "PEDIGREE",
        "WONDERFUL", 
        "POM", 
        "ANCHOR'S BAY",
        "AVALON",
        "LUCERNE",
        "HERBAL ESSENCES",
        "SELSUN BLUE",
        "PRIME",
        "DEL MONTE", 
        "IMAGINE",
        "PURITAN'S PRIDE", 
        "BUSH'S BEST", 
        "CHEF BOYARDEE",
        "GREEN GIANT",
        "DEL MONTE",
        "HEINZ",
        "TAST!EZ", 
        "CRAVE",
        "SMART ONES",
        "MINUTE MAID",
        "CLUB HOUSE",
        "CESAR",
        "CELSIUS",
        "CASCADE",
        "WELCH'S",
        "PURE PROTEIN",
        "GODIVA",
        "ARM & HAMMER",
        "ALMOND BREEZE",
        "44TH STREET",
        "GREAT VALUE",
        "MANNS",
        "SWANSON'S",
        "PLANTERS",
        "OCEAN SPRAY",
        "SWEET BABY RAY'S",
        "HARTZ",
        "NEILMED",
        "OLAY",
        "NEUTROGENA",
        "AUSSIE",
        "BATISTE",
        "ENERGIZER",
        "DURACELL",
        "KODIAK",
        "POST",
        "CINNAMON TOAST CRUNCH",
        "NUTELLA",
        "SMUCKER'S",
        "NATURE VALLEY",
        "LUCKY CHARMS",
        "CREAM OF WHEAT",
        "CORN POPS",
        "KELLOGG'S",
        "KASHI",
        "KELLOGG",
        "CHEERIOS",
        "KRAVE",
        "HUNGRY JACK'S",
        "CAP'N CRUNCH",
        "FERRERO ROCHER",
        "GENERAL MILLS",
        "KIRKLAND"
      ];
      chrome.storage.sync.set({ usBrands: usDefaults }, () => {
        console.log("Set default US brands:", JSON.stringify(usDefaults, null, 2));
      });
    } else {
      console.log("Existing US brands found:", JSON.stringify(data.usBrands, null, 2));
    }

    if (!data.caBrands) {
      const caDefaults = [
        "TIM HORTONS",
        "MAPLE LEAF",
        "PRESIDENT\'S CHOICE",
        "LOBLAWS",
        "NO NAME",
        "COMPLIMENTS",
        "MCCAIN",
        "NEILSON",
        "NATREL",
        "CHAPMAN\'S",
        "SAPUTO",
        "KICKING HORSE COFFEE",
        "CANADA DRY",
        "AGROPUR",
        "OKA",
        "GAY LEA",
        "QUEBON",
        "YOPLAIT (CANADA)",
        "CLUB HOUSE",
        "SWISS CHALET",
        "HARVEY\'S",
        "MONTANA\'S",
        "MR. SUB",
        "MARY BROWN\'S",
        "DARE FOODS",
        "DAVIDSTEA",
        "FARM BOY",
        "FORTINOS",
        "GASPEREau VINEYARDS",
        "GRANVILLE ISLAND BREWING",
        "GUERRERO (CA)",
        "HABITANT",
        "HARVEY & VERN\'S",
        "JONES SODA (CAN)",
        "KERNALS POPCORN",
        "KRAFT CANADA",
        "LITTLE NORTHERN BAKEHOUSE",
        "MCCORMICK CANADA",
        "METRO",
        "MORTIMER\'S",
        "MOTHER PARKERS",
        "NESTLÉ (CAN)",
        "OLYMEL",
        "OLIVIERI",
        "PACIFIC WESTERN BREWING",
        "PATTISON FOOD GROUP",
        "PEAK FREANS (CAN)",
        "PENGUIN ICE CREAM",
        "QUEBEC MAPLE SYRUP",
        "RED ROSE TEA (CAN)",
        "ROBERTSON\'S",
        "ROYALE TISSUE",
        "SCHNEIDERS",
        "SCOTSBURN",
        "SELECTION (METRO)",
        "SMARTIES (CA VERSION)",
        "SO NICE (CAN)",
        "SOBEYS",
        "SUN RYPE",
        "THRIFTY FOODS",
        "VACHON",
        "WESTON FOODS",
        "WHITEWATER BREWING",
        "ACE BAKERY",
        "CANADA GOOSE",
        "BLACK FLY BEVERAGES",
        "BRIDOR",
        "BULK BARN",
        "CANADIAN CLUB",
        "CANADA SELECT",
        "CEDAR FOODS (CA)",
        "DAIRYLAND",
        "DEMPSTER\'S",
        "DOMINION (GROCERY)",
        "ELASTOBAK FOODS",
        "FORT GARRY BREWING",
        "FRESHCO",
        "GOLD SEAL (SEAFOOD)",
        "GREEN & BLACK\'S (CA DIV)",
        "HOP CITY BREWING",
        "IRRESISTIBLES",
        "JON MONTREAL BAGELS",
        "MARC ANGE",
        "MOUNTAINVIEW TURKEY",
        "NATUREGG",
        "NORREF SEAFOODS",
        "PACIFIC WILD",
        "POM BAKERY",
        "RICKARD\'S",
        "SEAGRAM",
        "SENSATIONS (SAFEWAY)",
        "ST. HUBERT",
        "VILLAGGIO",
        "VOORTMAN",
        "WESTERN FAMILY",
        "ZARKY\'S",
        "ZIGGY\'S",
        "WEBBER NATURALS",
        "SMARTSWEETS",
        "RENEES",
        "BURNBRAE FARMS",
        "MISS VICKIE'S",
        "QUE PASA",
        "OLD DUTCH",
        "NEAL BROTHERS",
        "KETTLE BRAND",
        "UNICO",
        "FOREMOST DAIRIES",
        "GREAT GENTLEMAN",
        "GRACE ISLAND",
        "NABOB",
        "MCCAFE",
        "PILLERS",
        "RITZ",
        "CHRISTIE",
        "CHRISTIE'S",
        "DEMPSTER'S", 
        "OIKOS", 
        "ACTIVIA",
        "DANONE", 
        "YOPLAIT",
        "CLOVER LEAF", 
        "SILVER HILLS BAKERY",
        "LITTLE NORTHERN BAKEHOUSE",
        "HABITANT", 
        "GOLDEN DRAGON", 
        "CATELlI",
        "DRUMSTICK",
        "SPITZ",
        "CALEDON FARMS",
        "SUNRISE TOFU",
        "SHORBA",
        "AYLMER", 
        "MR. NOODLES", 
        "M'LORD",
        "EVIVE",
        "WINDSOR",
        "ROGERS",
        "OLIVIERI",
        "ANTONIO",
        "YVES",
        "IOGO",
        "SEALTEST",
        "REMEDY ORGANICS",
        "CASA MENDOZA",
        "MADEGOOD",
        "DECACER",
        "NATURE'S PATH",
        "QUINN'S",
        "BALDERSON"
      ];
      chrome.storage.sync.set({ caBrands: caDefaults }, () => {
        console.log("Set default CA brands:", JSON.stringify(caDefaults, null, 2));
      });
    } else {
      console.log("Existing CA brands found:", JSON.stringify(data.caBrands, null, 2));
    }
  });
});

chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.type === "updateBrands") {
    console.log("Instacart Extension: Received brand updates from Options page.");
    chrome.storage.sync.set(
      {
        usBrands: request.usBrands,
        caBrands: request.caBrands
      },
      () => {
        console.log("Updated brand arrays from options page.");
        sendResponse({ status: "ok" });
      }
    );
    return true;
  }
});
